import "./globals.css";
import type { Metadata } from "next";
import { GameProvider } from "./context/GameContext";
export const metadata: Metadata = {
  title: "Farming Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <GameProvider>
          {children}
        </GameProvider>
      </body>
    </html>
  );
}